use components::Parameter;

parameter_builder!(AltRep, String::from("ALTREP"));
parameter_builder!(CN, String::from("CN"));
parameter_builder!(CUType, String::from("CUTYPE"));
parameter_builder!(DelegatedFrom, String::from("DELEGATED-FROM"));
parameter_builder!(DelegatedTo, String::from("DELEGATED-TO"));
parameter_builder!(Dir, String::from("DIR"));
parameter_builder!(Encoding, String::from("ENCODING"));
parameter_builder!(FmtType, String::from("FMTTYPE"));
parameter_builder!(FBType, String::from("FBTYPE"));
parameter_builder!(Language, String::from("LANGUAGE"));
parameter_builder!(Member, String::from("MEMBER"));
parameter_builder!(PartStat, String::from("PARTSTAT"));
parameter_builder!(Range, String::from("RANGE"));
parameter_builder!(Related, String::from("RELATED"));
parameter_builder!(RelType, String::from("RELTYPE"));
parameter_builder!(Role, String::from("ROLE"));
parameter_builder!(RSVP, String::from("RSVP"));
parameter_builder!(SentBy, String::from("SENT-BY"));
parameter_builder!(TZID, String::from("TZID"));
parameter_builder!(Value, String::from("VALUE"));

impl_default_parameter!(AltRep);
impl_default_parameter!(CN);
impl_default_parameter!(CUType, String::from("INDIVIDUAL"));
impl_default_parameter!(DelegatedFrom);
impl_default_parameter!(DelegatedTo);
impl_default_parameter!(Dir);
impl_default_parameter!(Encoding, String::from("8BIT"));
impl_default_parameter!(FmtType);
impl_default_parameter!(FBType, String::from("BUSY"));
impl_default_parameter!(Language);
impl_default_parameter!(Member);
impl_default_parameter!(PartStat, String::from("NEEDS-ACTION"));
impl_default_parameter!(Range, String::from("THISANDFUTURE"));
impl_default_parameter!(Related, String::from("START"));
impl_default_parameter!(RelType, String::from("PARENT"));
impl_default_parameter!(Role, String::from("REQ-PARTICIPANT"));
impl_default_parameter!(RSVP, String::from("FALSE"));
impl_default_parameter!(SentBy);
impl_default_parameter!(TZID);
impl_default_parameter!(Value);
